### ISSUE TITLE
Missing v0.5.0 tag

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_tesserocr#85] opened 2019-10-29 16:25 UTC
PyPI has [0.5.0](https://pypi.org/project/ocrd-tesserocr/0.5.0), while this repo has [0.4.0](https://github.com/OCR-D/ocrd_tesserocr/releases) as the latest version. (Found this while investigating a problem with 0.5.0)

Related: The [releases page](https://github.com/OCR-D/ocrd_tesserocr/releases) in this repo says that 0.2.2 is the newest version while also offering to show newer tags – with 0.3.0 and 0.4.0 🙈 I have no idea what GitHub is doing here.

**Comment by bertsky** [comment] 2019-10-29 17:52
I can explain:
- PyPI release 0.5.0 is a pre-release from #83 / `edge` (which itself is a re-incarnation of #80). It requires core:edge (`ocrd==2.0.0a1`). (The reason for the `edge' branches is that maintainers were still skeptical about OCR-D/core#327 and wanted time for testing, while still being able to roll out.)
- 533d83c049ba93c86e0d77e40ada7ef8e122dc87 should have become PyPI release 0.4.1, but was forgotten
- PyPI release 0.4.0 is the latest release from `master`, but already quite dated
- Github can only make releases for things that have a version tag. This has been neglected for a while. I will fix this now...

**Comment by bertsky** [comment] 2019-10-30 07:47
>     * [533d83c](https://github.com/OCR-D/ocrd_tesserocr/commit/533d83c049ba93c86e0d77e40ada7ef8e122dc87) should have become PyPI release 0.4.1, but was forgotten

I am not sure whether we should still release the current master as `0.4.1`. It makes little sense now that we already have `0.5.0`. But maybe @kba has another opinion?

>     * Github can only make releases for things that have a version tag. This has been neglected for a while. I will fix this now...

Actually the tags are there, but not automatically turned into GH releases. I don't what reasons @kba has for publishing some but not all tags as GH releases.

Meanwhile, I added a fix to current master which ensures that `ocrd` does not come from core:edge, so at least we have both branches working in CI.

**Comment by mikegerber** [comment] 2019-10-30 09:43
> PyPI release 0.5.0 is a pre-release

It's not a pre-release on PyPI :) (For some reason, in one of my installations, it does not pull in ocrd 2.0.1a, and so I get non-functional ocrd-tesserocr-* tools – this was the cause for me to look for 0.5.0 here)

**Comment by bertsky** [comment] 2019-10-30 09:58
`0.5.0` is by definition a pre-release, as is everything below 1.0. So the problem is that we cannot prevent installers from using the newest version. We should have made a "stable" 1.0 out of the current `master`, and release `edge` as 1.1a1 or so.

I guess we have to wait until @kba gets back for a strategy how to proceed with pilots.

**Comment by kba** [comment] 2019-10-31 14:21
> I am not sure whether we should still release the current master as 0.4.1. It makes little sense now that we already have 0.5.0. But maybe @kba has another opinion?

No, that's why I went ahead with 0.5.0. As @bertsky said, everythin below 1.0 is pre-release and by definition unstable. We want the early adopters to use the newest version of tesserocr (and cis_ocrd BTW) which use the newest pre-release of core.

I would strongly prefer to get rid of the `edge` branches and `..a1` releases ASAP.

For now, I'll update the tags (probably just forgot to push `v.0.5.0`) and mark it as a pre-release and we'll hopefully have a clear path forward with the outstanding PR in core by the end of the week.

**Comment by kba** [comment] 2019-10-31 16:40
Fixed now, releases released here as well.

**Closed by kba** 2019-10-31 16:40 UTC
