### ISSUE TITLE
ocrd-tesserocr-segment-region TypeError: __init__() got multiple values for argument 'workspace'

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_tesserocr#193] opened 2023-03-22 17:22 UTC
~~~
% ocrd-tesserocr-segment-region   -I OCR-D-IMG-BINPAGE-sauvola -O OCR-D-IMG-BINPAGE-sauvola-SEG-REGION-tess                                
[...]
TypeError: __init__() got multiple values for argument 'workspace'
~~~

Perhaps also already known and possibly fixed by #191?

**Comment by mikegerber** [comment] 2023-03-22 17:23
👀 @bertsky

**Comment by bertsky** [comment] 2023-03-22 17:26
duplicate of #190

**Closed by bertsky** 2023-03-22 17:26 UTC

**Comment by mikegerber** [comment] 2023-03-24 15:31
Fixed in newest release, thanks!
